## 7a. Linear Regression Model Training and Testing

Code are following AAI 540 Lab 4

### Setup to Load Data from S3

In [1]:
# !pip install --upgrade pip

In [2]:
# !pip install -q PyAthena

In [8]:
import boto3
import sagemaker
import pandas as pd
from pyathena import connect
sess = sagemaker.Session()
bucket = sess.default_bucket()
role = sagemaker.get_execution_role()
region = boto3.Session().region_name

In [9]:

# Set S3 path to Parquet data
s3_path_parquet = f's3://{bucket}/CCPP/data//parquet'
# Set Athena parameters
# Set Athena parameters
database_name = "ccpp_aws_fp"
table_name_csv = "final_data_csv"
table_name_parquet = "final_data_parquet_v1"

In [10]:
# Set S3 staging directory -- this is a temporary directory used for Athena queries
s3_staging_dir = "s3://{0}/athena/staging".format(bucket)

In [11]:
conn = connect(region_name=region, s3_staging_dir=s3_staging_dir)

In [ ]:
from pyathena import connect

In [14]:

statement = """SELECT count(1) FROM {}.{}
    """.format(
    database_name, table_name_parquet
)

print(statement)

SELECT count(1) FROM ccpp_aws_fp.final_data_parquet_v1

In [18]:

data_count= pd.read_sql(statement, conn)
total_records=data_count['_col0'].values[0]
total_records

/tmp/ipykernel_20296/3056553487.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_count= pd.read_sql(statement, conn)

14764

In [21]:
train_seq_id= int(total_records*0.4)
val_seq_id= train_seq_id+ int(total_records*0.4)

### Load Training Dataset (all year 2013 data)

In [30]:


statement = """SELECT * FROM {}.{}
    WHERE seq_id < {}
    ORDER BY seq_id""".format(
    database_name, table_name_parquet,train_seq_id
)

print(statement)

SELECT * FROM ccpp_aws_fp.final_data_parquet_v1
    WHERE seq_id < 5905
    ORDER BY seq_id

In [31]:
data_train = pd.read_sql(statement, conn)
data_train

/tmp/ipykernel_20296/3564220957.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_train = pd.read_sql(statement, conn)

,seq_id,ingestion_ts,gt_comp_dis_pressure,gt_exhaust_pressure,gt_inlet_temp,gt_air_filter_diff_pressure,solar_radiation,solar_energy,uv_index,gt_ambient_pressure,cloud_cover,sea_level_pressure,gt_energy_yield
0,1,2026-02-04 06:51:25.215,10.0720,18.132,1027.8,2.6356,346.2,1.2,3.0,1024.7,24.7,1027.3,100.02
1,2,2026-02-04 06:51:25.215,10.3860,19.480,1006.5,3.6384,33.8,0.1,0.0,1017.7,24.2,1028.0,100.03
2,3,2026-02-04 06:51:25.215,9.9408,17.982,1037.5,2.5758,761.2,2.7,8.0,1013.5,43.4,1017.8,100.04
3,4,2026-02-04 06:51:25.215,10.0930,18.091,1028.7,2.6372,543.4,2.0,5.0,1023.3,27.8,1027.1,100.07
4,5,2026-02-04 06:51:25.215,10.0720,18.232,1026.9,3.8423,0.0,0.0,0.0,1013.7,45.0,1021.9,100.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5899,5900,2026-02-04 06:51:25.215,11.6280,25.499,1074.8,2.9950,0.9,0.0,0.0,1017.2,55.7,1009.1,130.13
5900,5901,2026-02-04 06:51:25.215,11.5870,22.882,1073.6,3.1950,0.0,0.0,0.0,1033.3,52.3,1018.4,130.13
5901,5902,2026-02-04 06:51:25.215,11.6420,23.971,1076.3,3.4619,0.0,0.0,0.0,1012.3,0.0,1019.2,130.13
5902,5903,2026-02-04 06:51:25.215,11.5920,22.940,1072.4,2.9614,456.6,1.6,5.0,1008.1,87.9,992.2,130.13
5903,5904,2026-02-04 06:51:25.215,11.9850,25.214,1081.1,3.9441,0.0,0.0,0.0,1009.1,78.2,1014.2,130.13

### Load Validation Data 2014 January

In [35]:
statement = """SELECT * FROM {}.{}
    WHERE seq_id >= {} and seq_id < {}
    ORDER BY seq_id""".format(
    database_name, table_name_parquet,train_seq_id,val_seq_id
)

print(statement)

SELECT * FROM ccpp_aws_fp.final_data_parquet_v1
    WHERE seq_id >= 5905 and seq_id < 11810
    ORDER BY seq_id

In [36]:
data_val = pd.read_sql(statement, conn)
data_val

/tmp/ipykernel_20296/3443150230.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_val = pd.read_sql(statement, conn)

,seq_id,ingestion_ts,gt_comp_dis_pressure,gt_exhaust_pressure,gt_inlet_temp,gt_air_filter_diff_pressure,solar_radiation,solar_energy,uv_index,gt_ambient_pressure,cloud_cover,sea_level_pressure,gt_energy_yield
0,5905,2026-02-04 06:51:25.215,11.795,26.317,1070.5,3.1922,401.0,1.4,4.0,1002.9,23.9,1024.2,130.13
1,5906,2026-02-04 06:51:25.215,11.561,23.099,1072.6,3.0669,2.5,0.0,0.0,1008.5,89.1,999.3,130.13
2,5907,2026-02-04 06:51:25.215,11.714,22.995,1074.1,3.4150,0.0,0.0,0.0,1023.2,8.8,1028.2,130.14
3,5908,2026-02-04 06:51:25.215,12.017,26.025,1082.7,4.2980,2.6,0.0,0.0,1005.5,89.1,1008.0,130.14
4,5909,2026-02-04 06:51:25.215,11.619,28.618,1074.4,3.1668,223.1,0.8,2.0,1022.4,20.3,1013.2,130.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5900,11805,2026-02-04 06:51:25.215,13.237,30.768,1100.0,5.2301,353.4,1.3,4.0,1011.1,29.3,1010.8,147.96
5901,11806,2026-02-04 06:51:25.215,13.247,30.777,1099.9,4.9841,542.6,2.0,5.0,1005.5,85.5,1012.0,147.96
5902,11807,2026-02-04 06:51:25.215,13.239,30.058,1099.8,4.6899,0.0,0.0,0.0,1007.2,15.8,1009.9,147.96
5903,11808,2026-02-04 06:51:25.215,13.190,29.675,1100.0,4.2717,0.0,0.0,0.0,1011.3,24.0,1012.7,147.96
5904,11809,2026-02-04 06:51:25.215,13.279,30.233,1099.9,4.2018,0.0,0.0,0.0,1013.1,43.6,1010.0,147.96

### Load Test Data 2014 February

In [37]:
statement = """SELECT * FROM {}.{}
    WHERE seq_id >= {} 
    ORDER BY seq_id""".format(
    database_name, table_name_parquet,val_seq_id
)

print(statement)

SELECT * FROM ccpp_aws_fp.final_data_parquet_v1
    WHERE seq_id >= 11810
    ORDER BY seq_id

In [38]:
data_test = pd.read_sql(statement, conn)
data_test

/tmp/ipykernel_20296/2304454054.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_test = pd.read_sql(statement, conn)

,seq_id,ingestion_ts,gt_comp_dis_pressure,gt_exhaust_pressure,gt_inlet_temp,gt_air_filter_diff_pressure,solar_radiation,solar_energy,uv_index,gt_ambient_pressure,cloud_cover,sea_level_pressure,gt_energy_yield
0,11810,2026-02-04 06:51:25.215,13.206,29.560,1099.8,4.1605,0.0,0.0,0.0,1012.9,0.0,1015.0,147.96
1,11811,2026-02-04 06:51:25.215,13.181,30.379,1100.1,4.7453,747.3,2.7,7.0,1012.9,0.0,1009.7,147.97
2,11812,2026-02-04 06:51:25.215,13.198,29.797,1100.1,4.3650,787.9,2.8,8.0,1015.3,14.9,1012.9,147.97
3,11813,2026-02-04 06:51:25.215,13.233,30.344,1098.8,5.1058,170.9,0.6,2.0,1012.5,23.9,1012.7,147.98
4,11814,2026-02-04 06:51:25.215,13.246,30.035,1100.0,4.7132,683.5,2.5,7.0,1013.1,43.6,1016.0,147.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,14760,2026-02-04 06:51:25.215,15.039,36.573,1100.0,4.2813,0.0,0.0,0.0,1033.4,20.9,1038.3,177.49
2951,14761,2026-02-04 06:51:25.215,15.083,36.533,1100.0,4.3541,0.0,0.0,0.0,1034.1,89.1,1017.1,177.88
2952,14762,2026-02-04 06:51:25.215,15.029,37.105,1099.9,4.3915,0.0,0.0,0.0,1033.2,87.9,1015.3,177.91
2953,14763,2026-02-04 06:51:25.215,15.042,36.844,1100.0,4.3749,0.0,0.0,0.0,1034.0,89.1,1015.2,178.31
2954,14764,2026-02-04 06:51:25.215,15.159,37.505,1099.9,4.4238,0.0,0.0,0.0,1033.3,83.0,1015.3,179.50

### Prepare the dataset

In [39]:
data_train = data_train.drop(['seq_id', 'ingestion_ts'], axis=1)
data_train

,gt_comp_dis_pressure,gt_exhaust_pressure,gt_inlet_temp,gt_air_filter_diff_pressure,solar_radiation,solar_energy,uv_index,gt_ambient_pressure,cloud_cover,sea_level_pressure,gt_energy_yield
0,10.0720,18.132,1027.8,2.6356,346.2,1.2,3.0,1024.7,24.7,1027.3,100.02
1,10.3860,19.480,1006.5,3.6384,33.8,0.1,0.0,1017.7,24.2,1028.0,100.03
2,9.9408,17.982,1037.5,2.5758,761.2,2.7,8.0,1013.5,43.4,1017.8,100.04
3,10.0930,18.091,1028.7,2.6372,543.4,2.0,5.0,1023.3,27.8,1027.1,100.07
4,10.0720,18.232,1026.9,3.8423,0.0,0.0,0.0,1013.7,45.0,1021.9,100.14
...,...,...,...,...,...,...,...,...,...,...,...
5899,11.6280,25.499,1074.8,2.9950,0.9,0.0,0.0,1017.2,55.7,1009.1,130.13
5900,11.5870,22.882,1073.6,3.1950,0.0,0.0,0.0,1033.3,52.3,1018.4,130.13
5901,11.6420,23.971,1076.3,3.4619,0.0,0.0,0.0,1012.3,0.0,1019.2,130.13
5902,11.5920,22.940,1072.4,2.9614,456.6,1.6,5.0,1008.1,87.9,992.2,130.13
5903,11.9850,25.214,1081.1,3.9441,0.0,0.0,0.0,1009.1,78.2,1014.2,130.13

In [40]:
data_val = data_val.drop(['seq_id', 'ingestion_ts'], axis=1)
data_val

,gt_comp_dis_pressure,gt_exhaust_pressure,gt_inlet_temp,gt_air_filter_diff_pressure,solar_radiation,solar_energy,uv_index,gt_ambient_pressure,cloud_cover,sea_level_pressure,gt_energy_yield
0,11.795,26.317,1070.5,3.1922,401.0,1.4,4.0,1002.9,23.9,1024.2,130.13
1,11.561,23.099,1072.6,3.0669,2.5,0.0,0.0,1008.5,89.1,999.3,130.13
2,11.714,22.995,1074.1,3.4150,0.0,0.0,0.0,1023.2,8.8,1028.2,130.14
3,12.017,26.025,1082.7,4.2980,2.6,0.0,0.0,1005.5,89.1,1008.0,130.14
4,11.619,28.618,1074.4,3.1668,223.1,0.8,2.0,1022.4,20.3,1013.2,130.14
...,...,...,...,...,...,...,...,...,...,...,...
5900,13.237,30.768,1100.0,5.2301,353.4,1.3,4.0,1011.1,29.3,1010.8,147.96
5901,13.247,30.777,1099.9,4.9841,542.6,2.0,5.0,1005.5,85.5,1012.0,147.96
5902,13.239,30.058,1099.8,4.6899,0.0,0.0,0.0,1007.2,15.8,1009.9,147.96
5903,13.190,29.675,1100.0,4.2717,0.0,0.0,0.0,1011.3,24.0,1012.7,147.96
5904,13.279,30.233,1099.9,4.2018,0.0,0.0,0.0,1013.1,43.6,1010.0,147.96

In [41]:
data_test = data_test.drop(['seq_id', 'ingestion_ts'], axis=1)
data_test

,gt_comp_dis_pressure,gt_exhaust_pressure,gt_inlet_temp,gt_air_filter_diff_pressure,solar_radiation,solar_energy,uv_index,gt_ambient_pressure,cloud_cover,sea_level_pressure,gt_energy_yield
0,13.206,29.560,1099.8,4.1605,0.0,0.0,0.0,1012.9,0.0,1015.0,147.96
1,13.181,30.379,1100.1,4.7453,747.3,2.7,7.0,1012.9,0.0,1009.7,147.97
2,13.198,29.797,1100.1,4.3650,787.9,2.8,8.0,1015.3,14.9,1012.9,147.97
3,13.233,30.344,1098.8,5.1058,170.9,0.6,2.0,1012.5,23.9,1012.7,147.98
4,13.246,30.035,1100.0,4.7132,683.5,2.5,7.0,1013.1,43.6,1016.0,147.98
...,...,...,...,...,...,...,...,...,...,...,...
2950,15.039,36.573,1100.0,4.2813,0.0,0.0,0.0,1033.4,20.9,1038.3,177.49
2951,15.083,36.533,1100.0,4.3541,0.0,0.0,0.0,1034.1,89.1,1017.1,177.88
2952,15.029,37.105,1099.9,4.3915,0.0,0.0,0.0,1033.2,87.9,1015.3,177.91
2953,15.042,36.844,1100.0,4.3749,0.0,0.0,0.0,1034.0,89.1,1015.2,178.31
2954,15.159,37.505,1099.9,4.4238,0.0,0.0,0.0,1033.3,83.0,1015.3,179.50

In [42]:
data_batch = data_test.drop(['gt_energy_yield'], axis=1)
data_batch

,gt_comp_dis_pressure,gt_exhaust_pressure,gt_inlet_temp,gt_air_filter_diff_pressure,solar_radiation,solar_energy,uv_index,gt_ambient_pressure,cloud_cover,sea_level_pressure
0,13.206,29.560,1099.8,4.1605,0.0,0.0,0.0,1012.9,0.0,1015.0
1,13.181,30.379,1100.1,4.7453,747.3,2.7,7.0,1012.9,0.0,1009.7
2,13.198,29.797,1100.1,4.3650,787.9,2.8,8.0,1015.3,14.9,1012.9
3,13.233,30.344,1098.8,5.1058,170.9,0.6,2.0,1012.5,23.9,1012.7
4,13.246,30.035,1100.0,4.7132,683.5,2.5,7.0,1013.1,43.6,1016.0
...,...,...,...,...,...,...,...,...,...,...
2950,15.039,36.573,1100.0,4.2813,0.0,0.0,0.0,1033.4,20.9,1038.3
2951,15.083,36.533,1100.0,4.3541,0.0,0.0,0.0,1034.1,89.1,1017.1
2952,15.029,37.105,1099.9,4.3915,0.0,0.0,0.0,1033.2,87.9,1015.3
2953,15.042,36.844,1100.0,4.3749,0.0,0.0,0.0,1034.0,89.1,1015.2
2954,15.159,37.505,1099.9,4.4238,0.0,0.0,0.0,1033.3,83.0,1015.3

In [43]:
prefix = "CCPP-enery-prediction-linear-regression"

In [44]:
train_file = "train_data.csv"
data_train.to_csv(train_file, index=False, header=False)
sess.upload_data(train_file, key_prefix="{}/train".format(prefix))

validation_file = "validation_data.csv"
data_val.to_csv(validation_file, index=False, header=False)
sess.upload_data(validation_file, key_prefix="{}/validation".format(prefix))

test_file = "test_data.csv"
data_test.to_csv(test_file, index=False, header=False)
sess.upload_data(test_file, key_prefix="{}/batch".format(prefix))

batch_file = "batch_data.csv"
data_batch.to_csv(batch_file, index=False, header=False)
sess.upload_data(batch_file, key_prefix="{}/batch".format(prefix))

's3://sagemaker-us-east-1-483525480215/CCPP-enery-prediction-linear-regression/batch/batch_data.csv'

### Model Training Setup and Training

In [47]:
%%time
from time import gmtime, strftime

job_name = "lr-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
output_location = "s3://{}/{}/output/{}".format(bucket, prefix, job_name)
image = sagemaker.image_uris.retrieve(
    framework="linear-learner",   # built-in algorithm for regression/classification
    region=boto3.Session().region_name,
    version="latest"               # always safe to use "latest"
)

linear_estimator = sagemaker.estimator.Estimator(
    image,
    role,
    instance_count=1,
    instance_type="ml.m5.large",
    volume_size=50,
    input_mode="File",
    output_path=output_location,
    sagemaker_session=sess,
)
linear_estimator.set_hyperparameters(
    predictor_type="regressor",   # must set this for regression
    mini_batch_size=100,          # batch size for training
    epochs=15,                    # number of passes over the dataset
    learning_rate=0.01,           # similar to eta
    optimizer="adam"              # can also be 'sgd', 'ftrl'
)
train_data = sagemaker.inputs.TrainingInput(
    "s3://{}/{}/train".format(bucket, prefix),
    distribution="FullyReplicated",
    content_type="text/csv",
    s3_data_type="S3Prefix",
)
validation_data = sagemaker.inputs.TrainingInput(
    "s3://{}/{}/validation".format(bucket, prefix),
    distribution="FullyReplicated",
    content_type="text/csv",
    s3_data_type="S3Prefix",
)
data_channels = {"train": train_data, "validation": validation_data}

# Start training by calling the fit method in the estimator
linear_estimator.fit(inputs=data_channels, job_name=job_name, logs=True)

INFO:sagemaker.image_uris:Same images used for training and inference. Defaulting to image scope: inference.
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.
INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: lr-2026-02-04-07-41-14

2026-02-04 07:41:16 Starting - Starting the training job...
2026-02-04 07:41:30 Starting - Preparing the instances for training...
2026-02-04 07:41:53 Downloading - Downloading input data...
2026-02-04 07:42:33 Downloading - Downloading the training image.........
2026-02-04 07:43:59 Training - Training image download completed. Training in progress.Docker entrypoint called with argument(s): train
Running default environment configuration script
[02/04/2026 07:44:04 INFO 140550108096320] Reading default configuration from /opt/amazon/lib/python3.8/site-packages/algorithm/resources/default-input.json: {'mini_batch_size': '1000', 'epochs': '15', 'feature_dim': 'auto', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false'}
[02/04/2026 07:44:04 INFO 140550108096320] Merging with provided configuration from /opt/ml/input/config/hyperparameters.json: {'epochs': '15', 'learning_rate': '0.01', 'mini_batch_size': '100', 'optimizer': 'adam', 'predictor_type': 'regressor'}
[02/04/2026 07:44:04 INFO 140550108096320] Final configuration: {'mini_batch_size': '100', 'epochs': '15', 'feature_dim': 'auto', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'adam', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': '0.01', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'regressor'}
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:495: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cons['type'] is 'ineq':
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:743: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.X_min) is not 0:
[02/04/2026 07:44:06 WARNING 140550108096320] Loggers have already been setup.
[02/04/2026 07:44:06 INFO 140550108096320] Final configuration: {'mini_batch_size': '100', 'epochs': '15', 'feature_dim': 'auto', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'adam', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': '0.01', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'regressor'}
[02/04/2026 07:44:06 WARNING 140550108096320] Loggers have already been setup.
Process 7 is a worker.
[02/04/2026 07:44:06 INFO 140550108096320] Using default worker.
[02/04/2026 07:44:07 INFO 140550108096320] Checkpoint loading and saving are disabled.
[02/04/2026 07:44:07 INFO 140550108096320] Create Store: local
[02/04/2026 07:44:07 INFO 140550108096320] Scaler algorithm parameters
 <algorithm.scaler.ScalerAlgorithmStable object at 0x7fd3d7e2c580>
[02/04/2026 07:44:07 INFO 140550108096320] Scaling model computed with parameters:
 {'stdev_label':
[0.5951832]
<NDArray 1 @cpu(0)>, 'stdev_weight':
[  2.356576   14.52003     0.5808528 239.63835     0.8630341   2.412217
   6.7337065  35.591595    6.2241187   8.689489 ]
<NDArray 10 @cpu(0)>, 'mean_label':
[11.124606]
<NDArray 1 @cpu(0)>, 'mean_weight':
[2.24065189e+01 1.06191333e+03 3.30584455e+00 1.50948196e+02
 5.43050826e-01 1.50491548e+00 1.01363617e+03 4.82792969e+01
 1.01613214e+03 1.19480209e+02]
<NDArray 10 @cpu(0)>}
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[02/04/2026 07:44:07 INFO 140550108096320] nvidia-smi: took 0.032 seconds to run.
[02/04/2026 07:44:07 INFO 140550108096320] nvidia-smi identified 0 GPUs.
[02/04/2026 07:44:07 INFO 140550108096320] Number of GPUs being used: 0
#metrics {"StartTime": 1770191047.5432892, "EndTime": 1770191047.5433207, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "Meta": "init_train_data_iter"}, "Metrics": {"Total Records Seen": {"sum": 6004.0, "count": 1, "min": 6004, "max": 6004}, "Total Batches Seen": {"sum": 61.0, "count": 1, "min": 61, "max": 61}, "Max Records Seen Between Resets": {"sum": 5904.0, "count": 1, "min": 5904, "max": 5904}, "Max Batches Seen Between Resets": {"sum": 60.0, "count": 1, "min": 60, "max": 60}, "Reset Count": {"sum": 2.0, "count": 1, "min": 2, "max": 2}, "Number of Records Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}, "Number of Batches Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}}}
#metrics {"StartTime": 1770191048.4957814, "EndTime": 1770191048.4958363, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 0}, "Metrics": {"train_mse_objective": {"sum": 0.3114723455097716, "count": 1, "min": 0.3114723455097716, "max": 0.3114723455097716}}}
#metrics {"StartTime": 1770191048.495901, "EndTime": 1770191048.495912, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 1}, "Metrics": {"train_mse_objective": {"sum": 0.5130161187608363, "count": 1, "min": 0.5130161187608363, "max": 0.5130161187608363}}}
#metrics {"StartTime": 1770191048.4961596, "EndTime": 1770191048.4961774, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 2}, "Metrics": {"train_mse_objective": {"sum": 0.6081793100146924, "count": 1, "min": 0.6081793100146924, "max": 0.6081793100146924}}}
#metrics {"StartTime": 1770191048.4962184, "EndTime": 1770191048.496228, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 3}, "Metrics": {"train_mse_objective": {"sum": 0.6876694440033476, "count": 1, "min": 0.6876694440033476, "max": 0.6876694440033476}}}
#metrics {"StartTime": 1770191048.496261, "EndTime": 1770191048.4962704, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 4}, "Metrics": {"train_mse_objective": {"sum": 0.21164681289155604, "count": 1, "min": 0.21164681289155604, "max": 0.21164681289155604}}}
#metrics {"StartTime": 1770191048.4963093, "EndTime": 1770191048.4963467, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 5}, "Metrics": {"train_mse_objective": {"sum": 0.23075124207189526, "count": 1, "min": 0.23075124207189526, "max": 0.23075124207189526}}}
#metrics {"StartTime": 1770191048.4963818, "EndTime": 1770191048.4963915, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 6}, "Metrics": {"train_mse_objective": {"sum": 0.23836714045476104, "count": 1, "min": 0.23836714045476104, "max": 0.23836714045476104}}}
#metrics {"StartTime": 1770191048.4964232, "EndTime": 1770191048.4964323, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 7}, "Metrics": {"train_mse_objective": {"sum": 0.21714266639644816, "count": 1, "min": 0.21714266639644816, "max": 0.21714266639644816}}}
#metrics {"StartTime": 1770191048.4964657, "EndTime": 1770191048.4964755, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 8}, "Metrics": {"train_mse_objective": {"sum": 0.4930889456554995, "count": 1, "min": 0.4930889456554995, "max": 0.4930889456554995}}}
#metrics {"StartTime": 1770191048.4965057, "EndTime": 1770191048.4965148, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 9}, "Metrics": {"train_mse_objective": {"sum": 0.35509989972841943, "count": 1, "min": 0.35509989972841943, "max": 0.35509989972841943}}}
#metrics {"StartTime": 1770191048.4965885, "EndTime": 1770191048.4965994, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 10}, "Metrics": {"train_mse_objective": {"sum": 0.6353157728809421, "count": 1, "min": 0.6353157728809421, "max": 0.6353157728809421}}}
#metrics {"StartTime": 1770191048.4966323, "EndTime": 1770191048.4966419, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 11}, "Metrics": {"train_mse_objective": {"sum": 0.5207308263697866, "count": 1, "min": 0.5207308263697866, "max": 0.5207308263697866}}}
#metrics {"StartTime": 1770191048.496673, "EndTime": 1770191048.4966817, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 12}, "Metrics": {"train_mse_objective": {"sum": 0.2381182883553586, "count": 1, "min": 0.2381182883553586, "max": 0.2381182883553586}}}
#metrics {"StartTime": 1770191048.496716, "EndTime": 1770191048.4967256, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 13}, "Metrics": {"train_mse_objective": {"sum": 0.17656314053777922, "count": 1, "min": 0.17656314053777922, "max": 0.17656314053777922}}}
#metrics {"StartTime": 1770191048.4967566, "EndTime": 1770191048.4967885, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 14}, "Metrics": {"train_mse_objective": {"sum": 0.2208765470375449, "count": 1, "min": 0.2208765470375449, "max": 0.2208765470375449}}}
#metrics {"StartTime": 1770191048.4968235, "EndTime": 1770191048.496833, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 15}, "Metrics": {"train_mse_objective": {"sum": 0.2473792588104636, "count": 1, "min": 0.2473792588104636, "max": 0.2473792588104636}}}
#metrics {"StartTime": 1770191048.4968655, "EndTime": 1770191048.4968748, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 16}, "Metrics": {"train_mse_objective": {"sum": 0.694641502994602, "count": 1, "min": 0.694641502994602, "max": 0.694641502994602}}}
#metrics {"StartTime": 1770191048.496906, "EndTime": 1770191048.4969144, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 17}, "Metrics": {"train_mse_objective": {"sum": 0.5952208654759293, "count": 1, "min": 0.5952208654759293, "max": 0.5952208654759293}}}
#metrics {"StartTime": 1770191048.4969459, "EndTime": 1770191048.496955, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 18}, "Metrics": {"train_mse_objective": {"sum": 0.7567416760072869, "count": 1, "min": 0.7567416760072869, "max": 0.7567416760072869}}}
#metrics {"StartTime": 1770191048.4969888, "EndTime": 1770191048.4969966, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 19}, "Metrics": {"train_mse_objective": {"sum": 0.6769091556031825, "count": 1, "min": 0.6769091556031825, "max": 0.6769091556031825}}}
#metrics {"StartTime": 1770191048.4970274, "EndTime": 1770191048.4970624, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 20}, "Metrics": {"train_mse_objective": {"sum": 0.22307826284634866, "count": 1, "min": 0.22307826284634866, "max": 0.22307826284634866}}}
#metrics {"StartTime": 1770191048.4970965, "EndTime": 1770191048.4971058, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 21}, "Metrics": {"train_mse_objective": {"sum": 0.19855392157021215, "count": 1, "min": 0.19855392157021215, "max": 0.19855392157021215}}}
#metrics {"StartTime": 1770191048.4971383, "EndTime": 1770191048.4971466, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 22}, "Metrics": {"train_mse_objective": {"sum": 0.21954137939517782, "count": 1, "min": 0.21954137939517782, "max": 0.21954137939517782}}}
#metrics {"StartTime": 1770191048.4971764, "EndTime": 1770191048.4971843, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 23}, "Metrics": {"train_mse_objective": {"sum": 0.229482553288088, "count": 1, "min": 0.229482553288088, "max": 0.229482553288088}}}
#metrics {"StartTime": 1770191048.4972155, "EndTime": 1770191048.497224, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 24}, "Metrics": {"train_mse_objective": {"sum": 0.960423323421155, "count": 1, "min": 0.960423323421155, "max": 0.960423323421155}}}
#metrics {"StartTime": 1770191048.497257, "EndTime": 1770191048.4972663, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 25}, "Metrics": {"train_mse_objective": {"sum": 1.00002736536123, "count": 1, "min": 1.00002736536123, "max": 1.00002736536123}}}
#metrics {"StartTime": 1770191048.497298, "EndTime": 1770191048.497306, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 26}, "Metrics": {"train_mse_objective": {"sum": 1.0767430701498257, "count": 1, "min": 1.0767430701498257, "max": 1.0767430701498257}}}
#metrics {"StartTime": 1770191048.4973369, "EndTime": 1770191048.497345, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 27}, "Metrics": {"train_mse_objective": {"sum": 1.0415362672482507, "count": 1, "min": 1.0415362672482507, "max": 1.0415362672482507}}}
#metrics {"StartTime": 1770191048.4974222, "EndTime": 1770191048.497433, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 28}, "Metrics": {"train_mse_objective": {"sum": 0.1898212954553507, "count": 1, "min": 0.1898212954553507, "max": 0.1898212954553507}}}
#metrics {"StartTime": 1770191048.4974651, "EndTime": 1770191048.497475, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 29}, "Metrics": {"train_mse_objective": {"sum": 0.18153890795626884, "count": 1, "min": 0.18153890795626884, "max": 0.18153890795626884}}}
#metrics {"StartTime": 1770191048.497508, "EndTime": 1770191048.4975169, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 30}, "Metrics": {"train_mse_objective": {"sum": 0.1649012688054877, "count": 1, "min": 0.1649012688054877, "max": 0.1649012688054877}}}
#metrics {"StartTime": 1770191048.497549, "EndTime": 1770191048.4975584, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 31}, "Metrics": {"train_mse_objective": {"sum": 0.16609557325557125, "count": 1, "min": 0.16609557325557125, "max": 0.16609557325557125}}}
[02/04/2026 07:44:08 INFO 140550108096320] #quality_metric: host=algo-1, epoch=0, train mse_objective <loss>=0.3114723455097716
#metrics {"StartTime": 1770191049.0608552, "EndTime": 1770191049.060898, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 0}, "Metrics": {"validation_mse_objective": {"sum": 0.1258149271693702, "count": 1, "min": 0.1258149271693702, "max": 0.1258149271693702}}}
#metrics {"StartTime": 1770191049.0609593, "EndTime": 1770191049.060971, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 1}, "Metrics": {"validation_mse_objective": {"sum": 0.1008012845090241, "count": 1, "min": 0.1008012845090241, "max": 0.1008012845090241}}}
#metrics {"StartTime": 1770191049.0610087, "EndTime": 1770191049.061019, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 2}, "Metrics": {"validation_mse_objective": {"sum": 0.14234903155495612, "count": 1, "min": 0.14234903155495612, "max": 0.14234903155495612}}}
#metrics {"StartTime": 1770191049.0610542, "EndTime": 1770191049.061085, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 3}, "Metrics": {"validation_mse_objective": {"sum": 0.15360361377028062, "count": 1, "min": 0.15360361377028062, "max": 0.15360361377028062}}}
#metrics {"StartTime": 1770191049.0612624, "EndTime": 1770191049.0614228, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 4}, "Metrics": {"validation_mse_objective": {"sum": 0.21778037261397631, "count": 1, "min": 0.21778037261397631, "max": 0.21778037261397631}}}
#metrics {"StartTime": 1770191049.0614717, "EndTime": 1770191049.0614853, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 5}, "Metrics": {"validation_mse_objective": {"sum": 0.27063804557018617, "count": 1, "min": 0.27063804557018617, "max": 0.27063804557018617}}}

### Setup Batch Transfomer Estimator

In [48]:
%%time

linear_transformer = linear_estimator.transformer(1, "ml.m4.xlarge")

# start a transform job
input_location = "s3://{}/{}/batch/{}".format(
    bucket, prefix, batch_file
)  # use input data without ID column
linear_transformer.transform(input_location, content_type="text/csv", split_type="Line")
linear_transformer.wait()

INFO:sagemaker:Creating model with name: linear-learner-2026-02-04-07-45-33-219
INFO:sagemaker:Creating transform job with name: linear-learner-2026-02-04-07-45-33-934

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/conda/lib/python3.12/site-packages/IPython/core/magics/execution.py:1370 in time            │
│                                                                                                  │
│   1367 │   │   else:                                                                             │
│   1368 │   │   │   st = clock2()                                                                 │
│   1369 │   │   │   try:                                                                          │
│ ❱ 1370 │   │   │   │   exec(code, glob, local_ns)                                                │
│   1371 │   │   │   │   out = None                                                                │
│   1372 │   │   │   │   # multi-line %%time case                                                  │
│   1373 │   │   │   │   if expr_val is not None:                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/workflow/pipeline_context.py:346 in wrapper    │
│                                                                                                  │
│   343 │   │   │                                                                                  │
│   344 │   │   │   return _StepArguments(retrieve_caller_name(self_instance), run_func, *args,    │
│   345 │   │                                                                                      │
│ ❱ 346 │   │   return run_func(*args, **kwargs)                                                   │
│   347 │                                                                                          │
│   348 │   return wrapper                                                                         │
│   349                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/transformer.py:302 in transform                │
│                                                                                                  │
│   299 │   │   │   sagemaker_session=self.sagemaker_session,                                      │
│   300 │   │   )                                                                                  │
│   301 │   │                                                                                      │
│ ❱ 302 │   │   self.latest_transform_job = _TransformJob.start_new(                               │
│   303 │   │   │   self,                                                                          │
│   304 │   │   │   data,                                                                          │
│   305 │   │   │   data_type,                                                                     │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/transformer.py:636 in start_new                │
│                                                                                                  │
│   633 │   │   │   batch_data_capture_config,                                                     │
│   634 │   │   )                                                                                  │
│   635 │   │                                                                                      │
│ ❱ 636 │   │   transformer.sagemaker_session.transform(**transform_args)                          │
│   637 │   │                                                                                      │
│   638 │   │   return cls(transformer.sagemaker_session, transformer._current_job_name)           │
│   639                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:3966 in transform                   │
│                                                                                                  │
│   3963 │   │   │   logger.debug("Transform request: %s", json.dumps(request, indent=4))          │
│   3964 │   │   │   self.sagemaker_client.create_transform_job(**request)                         │
│   3965 │   │                                                                                     │
│ ❱ 3966 │   │   self._intercept_create_request(transform_request, submit, self.transform.__name_  │
│   3967 │                                                                                         │
│   3968 │   def _create_model_request(                                                            │
│   3969 │   │   self,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:6819 in _intercept_create_request   │
│                                                                                                  │
│   6816 │   │   │   create (functor): a functor calls the sagemaker client create method          │
│   6817 │   │   │   func_name (str): the name of the function needed intercepting                 │
│   6818 │   │   """                                                                               │
│ ❱ 6819 │   │   return create(request)                                                            │
│   6820 │                                                                                         │
│   6821 │   def _create_inference_recommendations_job_request(                                    │
│   6822 │   │   self,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:3964 in submit                      │
│                                                                                                  │
│   3961 │   │   def submit(request):                                                              │
│   3962 │   │   │   logger.info("Creating transform job with name: %s", job_name)                 │
│   3963 │   │   │   logger.debug("Transform request: %s", json.dumps(request, indent=4))          │
│ ❱ 3964 │   │   │   self.sagemaker_client.create_transform_job(**request)                         │
│   3965 │   │                                                                                     │
│   3966 │   │   self._intercept_create_request(transform_request, submit, self.transform.__name_  │
│   3967                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/botocore/client.py:569 in _api_call                      │
│                                                                                                  │
│    566 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    567 │   │   │   │   )                                                                         │
│    568 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  569 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    570 │   │                                                                                     │
│    571 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    572                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/botocore/client.py:1023 in _make_api_call                │
│                                                                                                  │
│   1020 │   │   │   │   "Code"                                                                    │
│   1021 │   │   │   )                                                                             │
│   1022 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1023 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1024 │   │   else:                                                                             │
│   1025 │   │   │   return parsed_response                                                        │
│   1026                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ClientError: An error occurred (AccessDeniedException) when calling the CreateTransformJob operation: User:
arn:aws:sts::483525480215:assumed-role/LabRole/SageMaker is not authorized to perform: sagemaker:CreateTransformJob
on resource: arn:aws:sagemaker:us-east-1:483525480215:transform-job/linear-learner-2026-02-04-07-45-33-934 with an
explicit deny in an identity-based policy:
arn:aws:iam::483525480215:policy/c193294a4969078l13439518t1w483525480215-VocLabPolicy3-zaVpXj0KNTpW
(c193294a4969078l13439518t1w483525480215-VocLabPolicy3-zaVpXj0KNTpW)

### Plot the Batch Transform Result Compare to Ground Truth

In [49]:
import re


def get_csv_output_from_s3(s3uri, batch_file):
    file_name = "{}.out".format(batch_file)
    match = re.match("s3://([^/]+)/(.*)", "{}/{}".format(s3uri, file_name))
    output_bucket, output_prefix = match.group(1), match.group(2)
    s3.download_file(output_bucket, output_prefix, file_name)
    return pd.read_csv(file_name, sep=",", header=None)

In [50]:
s3 = boto3.client("s3")

In [51]:
output_df = get_csv_output_from_s3(linear_transformer.output_path, batch_file)
output_df.head(8)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 output_df = get_csv_output_from_s3(sm_transformer.output_path, batch_file)                   │
│   2 output_df.head(8)                                                                            │
│   3                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'sm_transformer' is not defined

In [31]:
output_df

            0
0    0.168284
1    0.168284
2    0.168284
3    0.168284
4    0.168284
..        ...
644  0.262286
645  0.262286
646  0.262286
647  0.262286
648  0.168284

[649 rows x 1 columns]

In [ ]:
compare_df = data_test[['gt_energy_yield']]

In [ ]:
compare_df

In [ ]:
combined_df = pd.concat([compare_df, output_df], axis=1)

In [ ]:
combined_df

In [ ]:
combined_df.rename(columns={0: 'Predited Energy'}, inplace=True)

In [ ]:
combined_df

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))

# Plotting the first column with a solid line
plt.plot(combined_df.index, combined_df['kwh'], linestyle='-', color='blue', label='Column 1 - Solid')

# Plotting the second column with a dotted line
plt.plot(combined_df.index, combined_df['Predited Energy'], linestyle=':', color='red', label='Column 2 - Dotted')
plt.legend()
# Show plot
plt.show()

In [28]:
%%html

<p><b>Shutting down your kernel for this notebook to release resources.</b></p>
<button class="sm-command-button" data-commandlinker-command="kernelmenu:shutdown" style="display:none;">Shutdown Kernel</button>
        
<script>
try {
    els = document.getElementsByClassName("sm-command-button");
    els[0].click();
}
catch(err) {
    // NoOp
}    
</script>